server:
  port: 8080
spring:
  #  datasource:
  #    password: Wang1599!!!!
  #    username: root
  #    url: jdbc:mysql://124.223.47.124:3306/spring_tutorial?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    password: Wang161301
    username: root
    url: jdbc:mysql://120.24.230.237:3306/mall?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

#  redis:
#    host: 124.223.47.124
#    port: 6379
#    database: 0
#    connect-timeout: 10000ms
#    lettuce:
#      pool:
#        # 最大连接数
#        max-active: 8
#        # 最大阻塞等待实际
#        max-wait: 10000ms
#        # 最大空闲连接
#        max-idle: 200
#        # 最小空闲连接
#        min-idle: 2
#    password: Wang1599!!!!

  kafka:
    bootstrap-servers: 124.223.47.124:9092
    producer:
      # 重试次数，设置大于0的值，则客户端会将发送失败的记录重新发送
      retries: 3
      batch-size: 16384 #批量处理大小，16K
      buffer-memory: 33554432 #缓冲存储大，32M
      acks: all
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 消费者组
      group-id: TestGroup
      # 是否自动提交
      enable-auto-commit: false
      # 消费偏移配置
      # none：如果没有为消费者找到先前的offset的值,即没有自动维护偏移量,也没有手动维护偏移量,则抛出异常
      # earliest：在各分区下有提交的offset时：从offset处开始消费；在各分区下无提交的offset时：从头开始消费
      # latest：在各分区下有提交的offset时：从offset处开始消费；在各分区下无提交的offset时：从最新的数据开始消费
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # manual_immediate：手动调用Acknowledgment.acknowledge()后立即提交，一般推荐使用这种
      ack-mode: manual_immediate



project:
#  filepath: /root/project/mallProject/backend/files
  filepath: C:\\Users\\24508\\IdeaProjects\\e-commerce-mall\\mall\\src\\main\\resources\\upload

